kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jetspotter.fullname" . }}
  labels: {{ include "jetspotter.labels" . | nindent 4 }}
data:
  LOCATION_LATITUDE: {{ .Values.jetspotter.location.latitude | quote }}
  LOCATION_LONGITUDE: {{ .Values.jetspotter.location.longitude | quote }}
  FETCH_INTERVAL:  {{ .Values.jetspotter.fetchInterval | quote }}
  MAX_RANGE_KILOMETERS: {{ .Values.jetspotter.maxRangeKilometers | quote }}
  AIRCRAFT_TYPES: {{ .Values.jetspotter.aircraftTypes | join "," }}
  MAX_AIRCRAFT_SLACK_MESSAGE: {{ .Values.slack.maxAircraftPerMessage | quote }}
  DISCORD_COLOR_ALTITUDE: {{ .Values.discord.colorAltitude | quote }}
  GOTIFY_URL: {{ .Values.gotify.url }}
