apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jetspotter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "jetspotter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jetspotter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jetspotter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          ports:
          - name: metrics
            containerPort: {{ .Values.metrics.port }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "jetspotter.fullname" . }}
            - secretRef:
                name: {{ include "jetspotter.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          