{
 "title": "Jetspotter Overview",
 "tags": [ "jetspotter" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aircraft_description",
    "label": "Aircraft type",
    "query": {
     "query": "label_values(jetspotter_aircraft_spotted_total,description)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jetspotter_aircraft_spotted_total,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Jets spotted",
   "type": "stat",
   "description": "Total jets spotted in time range",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(jetspotter_aircraft_spotted_total{description=~\"$aircraft_description\",service=\"$service\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jets by type",
   "type": "piechart",
   "description": "Jets by type in time range",
   "gridPos": { "h": 9, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type,description) (round(increase(jetspotter_aircraft_spotted_total{description=~\"$aircraft_description\", service=\"$service\"}[$__range])))",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Jets spotted",
   "type": "timeseries",
   "description": "Total jets that have been spotted in the specified time range",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(round(increase(jetspotter_aircraft_spotted_total{description=~\"$aircraft_description\",service=\"$service\"}[5m])))",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Jets all time",
   "type": "stat",
   "description": "Total amount of jets spotted",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jetspotter_aircraft_spotted_total{description=~\"$aircraft_description\", service=\"$service\"})",
     "legendFormat": "Jets spotted"
    }
   ]
  },
  {
   "title": "Jets all time",
   "type": "piechart",
   "description": "Distribution by aircraft type since the beginning of the metrics",
   "gridPos": { "h": 10, "w": 8, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (description, type) (jetspotter_aircraft_spotted_total{description=~\"$aircraft_description\", service=\"$service\"})",
     "legendFormat": "{{description}}"
    }
   ]
  }
 ]
}