name: 'PR flow'
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        shell: bash
        run: |
          go test ./internal/... --count 1

  build:
    name: Build
    needs: [test]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [darwin, linux, windows]
        architecture: [arm64, amd64]
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - uses: actions/checkout@v3

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.architecture }}
        id: build
        run: |
          BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
          VERSION="dev"
          COMMIT=$(git rev-parse --short HEAD)
          
          go build -o jetspotter-${{ matrix.os }}-${{ matrix.architecture }} \
            -ldflags "-X jetspotter/internal/version.Version=${VERSION} \
                      -X jetspotter/internal/version.Commit=${COMMIT} \
                      -X jetspotter/internal/version.BuildTime=${BUILD_TIME}" \
            cmd/jetspotter/jetspotter.go

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: "jetspotter-${{ matrix.os }}-${{ matrix.architecture }}"
          path: jetspotter-${{ matrix.os }}-${{ matrix.architecture }}

  image:
      name: Build container image
      runs-on: ubuntu-latest
      needs: [build]
      env:
        REGISTRY: ghcr.io
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Set build time environment variable
          run: echo "BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')" >> $GITHUB_ENV

        - name: Build container
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64,linux/arm64,linux/arm/v7
            push: false
            build-args: |
              VERSION=dev
              COMMIT=${{ github.sha }}
              BUILD_TIME=${{ env.BUILD_TIME }}
            tags: ${{ env.REGISTRY }}/${{ github.repository }}:dev
